/** Predefined list of common fashion brands for tag-flow autocomplete */
export const FASHION_BRANDS = [
  "& Other Stories",
  "A.P.C.",
  "Acne Studios",
  "Adidas",
  "Alexander Wang",
  "AllSaints",
  "American Eagle",
  "Anthropologie",
  "Arket",
  "ASOS",
  "Banana Republic",
  "Boden",
  "Bottega Veneta",
  "Burberry",
  "Calvin Klein",
  "COS",
  "Everlane",
  "Gap",
  "Gucci",
  "H&M",
  "J.Crew",
  "Levi's",
  "Loewe",
  "Madewell",
  "Mango",
  "Massimo Dutti",
  "Max Mara",
  "Nike",
  "Nordstrom",
  "Old Navy",
  "Patagonia",
  "Prada",
  "Primark",
  "Ralph Lauren",
  "Reformation",
  "Saint Laurent",
  "Sézane",
  "Shein",
  "Stüssy",
  "The North Face",
  "Theory",
  "Uniqlo",
  "Urban Outfitters",
  "Zara"
] as const;

export type FashionBrand = (typeof FASHION_BRANDS)[number];
